### ISSUE TITLE
Skjemaet for SendUtvalgssak - feil i forslagTilBehandlingsplan

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/gi-politiskbehandling#2]
Skjemaet no.ks.fiks.politisk.behandling.sendutvalgssak.v1.schema har en feil i forslagTilBehandlingsplan. Dette skal være et array med utvalg. Det mangler vel også en nummerering/rekkefølge som sorterer ønsket rekkefølge på utvalgene.

**Comment by torkjetil** [comment]
Oppdatert i modell og skjema for denne og sendOrienteringssak
