### ISSUE TITLE
Hent møteplan burde ha utvalgsId som kriterie

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/gi-politiskbehandling#4]
Nå er det utvalgsnavn som er kriteriet.
Jeg vil tro at UtvalgId er en unik id på utvalget som aldri endres, men utvalgs navn kan endres.

Det må være en forutsetning i standarden at møteId er unikt for hvert møte på tvers av utvalg. det kan ikke være to møter som har samme Id.

**Comment by torkjetil** [comment]
Lagt inn så både id og navn er mulig å bruke
