### ISSUE TITLE
Savner et felt på møte for møte-tittel

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/gi-politiskbehandling#5]
I Public 360 er det i alle fall et slikt felt som vises i brukergrensesnittet som f.eks. "Møte i Bystyret 02.12.2021"
Møte-Utvalgssystemet kan gjerne generere tittelen ut fra utvalg og møtedato hvis det ikke har et slikt felt.

**Comment by torkjetil** [comment]
Lagt inn i modell og skjema
